const MEDICINES = [
  { id:"m1", name:"Paracip 650", generic:"Paracetamol 650mg", company:"Cipla", salt:"Paracetamol (650mg)", category:"Pain relief / Fever", price:28,
    description:"Used for mild to moderate pain and fever reduction.",
    substitutes:[ {name:"Dolo 650", company:"Micro Labs", price:30}, {name:"Calpol 650", company:"GSK", price:33}, {name:"Crocin 650", company:"GSK", price:29} ],
    genericAlt:{name:"Paracetamol 650mg (Generic)", price:9} },
  { id:"m2", name:"Azithral 500", generic:"Azithromycin 500mg", company:"Alembic", salt:"Azithromycin (500mg)", category:"Antibiotic", price:78,
    description:"Broad spectrum antibiotic for bacterial infections of the respiratory tract, skin and ear.",
    substitutes:[ {name:"Azee 500", company:"Cipla", price:82}, {name:"Zithrocin 500", company:"FDC", price:75}, {name:"Azithral-XL", company:"Alembic", price:120} ],
    genericAlt:{name:"Azithromycin 500mg (Generic)", price:31} },
  { id:"m3", name:"Metfor 500", generic:"Metformin 500mg", company:"Sun Pharma", salt:"Metformin Hydrochloride (500mg)", category:"Diabetes", price:35,
    description:"First-line oral medicine for managing blood sugar in type 2 diabetes.",
    substitutes:[ {name:"Glycomet 500", company:"USV", price:32}, {name:"Glyciphage 500", company:"Franco-Indian", price:34}, {name:"Obimet 500", company:"Emcure", price:36} ],
    genericAlt:{name:"Metformin 500mg (Generic)", price:14} },
  { id:"m4", name:"Atorva 10", generic:"Atorvastatin 10mg", company:"Zydus", salt:"Atorvastatin Calcium (10mg)", category:"Cholesterol", price:66,
    description:"Statin used to lower LDL cholesterol and reduce cardiovascular risk.",
    substitutes:[ {name:"Storvas 10", company:"Sun Pharma", price:70}, {name:"Atorlip 10", company:"Cipla", price:64}, {name:"Tonact 10", company:"Lupin", price:68} ],
    genericAlt:{name:"Atorvastatin 10mg (Generic)", price:22} },
  { id:"m5", name:"Pantocid 40", generic:"Pantoprazole 40mg", company:"Sun Pharma", salt:"Pantoprazole Sodium (40mg)", category:"Acidity / GERD", price:88,
    description:"Proton pump inhibitor for acid reflux, gastritis and ulcers.",
    substitutes:[ {name:"Pan 40", company:"Alkem", price:84}, {name:"Pantop 40", company:"Aristo", price:90}, {name:"Pantodac 40", company:"Zydus", price:86} ],
    genericAlt:{name:"Pantoprazole 40mg (Generic)", price:29} },
  { id:"m6", name:"Augmentin 625", generic:"Amoxicillin + Clavulanic Acid", company:"GSK", salt:"Amoxicillin (500mg) + Clavulanic Acid (125mg)", category:"Antibiotic", price:198,
    description:"Combination antibiotic for tougher bacterial infections resistant to plain amoxicillin.",
    substitutes:[ {name:"Clavam 625", company:"Alkem", price:170}, {name:"Moxikind-CV 625", company:"Mankind", price:165}, {name:"Fightox 625", company:"Alembic", price:160} ],
    genericAlt:{name:"Amoxicillin+Clavulanate 625mg (Generic)", price:68} },
  { id:"m7", name:"Telma 40", generic:"Telmisartan 40mg", company:"Glenmark", salt:"Telmisartan (40mg)", category:"Blood pressure", price:112,
    description:"Angiotensin receptor blocker (ARB) used to treat high blood pressure.",
    substitutes:[ {name:"Telista 40", company:"Mankind", price:105}, {name:"Cresar 40", company:"Torrent", price:108}, {name:"Telsartan 40", company:"IPCA", price:98} ],
    genericAlt:{name:"Telmisartan 40mg (Generic)", price:38} },
  { id:"m8", name:"Montair LC", generic:"Montelukast + Levocetirizine", company:"Cipla", salt:"Montelukast (10mg) + Levocetirizine (5mg)", category:"Allergy / Asthma", price:145,
    description:"Combination therapy for allergic rhinitis and asthma-related symptoms.",
    substitutes:[ {name:"Ozon-LC", company:"Alkem", price:130}, {name:"Levomont", company:"Mankind", price:125}, {name:"Montek LC", company:"Sun Pharma", price:138} ],
    genericAlt:{name:"Montelukast+Levocetirizine (Generic)", price:47} },
  { id:"m9", name:"Ecosprin 75", generic:"Aspirin 75mg", company:"USV", salt:"Aspirin (75mg)", category:"Cardiac / Blood thinner", price:18,
    description:"Low-dose aspirin used for cardiovascular protection and blood clot prevention.",
    substitutes:[ {name:"Delisprin 75", company:"Torrent", price:16}, {name:"Aspispan 75", company:"Panacea Biotec", price:15}, {name:"Loprin 75", company:"IPCA", price:17} ],
    genericAlt:{name:"Aspirin 75mg (Generic)", price:6} },
  { id:"m10", name:"Thyronorm 50", generic:"Levothyroxine 50mcg", company:"Abbott", salt:"Levothyroxine Sodium (50mcg)", category:"Thyroid", price:112,
    description:"Hormone replacement for underactive thyroid (hypothyroidism).",
    substitutes:[ {name:"Eltroxin 50", company:"GSK", price:108}, {name:"Thyrox 50", company:"Macleods", price:95}, {name:"Lethyrox 50", company:"Zydus", price:98} ],
    genericAlt:{name:"Levothyroxine 50mcg (Generic)", price:35} },
  { id:"m11", name:"Cetzine", generic:"Cetirizine 10mg", company:"GSK", salt:"Cetirizine Hydrochloride (10mg)", category:"Allergy", price:20,
    description:"Antihistamine for allergic reactions, hay fever and hives.",
    substitutes:[ {name:"Alerid", company:"Cipla", price:18}, {name:"Okacet", company:"Cipla", price:19}, {name:"Zyrtec", company:"Dr Reddy's", price:24} ],
    genericAlt:{name:"Cetirizine 10mg (Generic)", price:7} },
  { id:"m12", name:"Shelcal 500", generic:"Calcium Carbonate + Vitamin D3", company:"Torrent", salt:"Calcium Carbonate (500mg) + Vitamin D3 (250 IU)", category:"Supplement", price:135,
    description:"Calcium and vitamin D supplement for bone health.",
    substitutes:[ {name:"Calcimax D3", company:"Emcure", price:120}, {name:"Zerodol Cal", company:"IPCA", price:110}, {name:"Ostocalcium", company:"Franco-Indian", price:125} ],
    genericAlt:{name:"Calcium+D3 (Generic)", price:48} },
];

const DOCTORS = [
  { id:"d1", name:"Dr. Ananya Sen", spec:"General Physician", exp:"12 yrs", fee:299, rating:4.8, initial:"AS" },
  { id:"d2", name:"Dr. Rohan Kapoor", spec:"Cardiologist", exp:"18 yrs", fee:599, rating:4.9, initial:"RK" },
  { id:"d3", name:"Dr. Meera Iyer", spec:"Dermatologist", exp:"9 yrs", fee:399, rating:4.7, initial:"MI" },
  { id:"d4", name:"Dr. Farhan Ali", spec:"Pediatrician", exp:"14 yrs", fee:349, rating:4.8, initial:"FA" },
  { id:"d5", name:"Dr. Priya Nair", spec:"Endocrinologist", exp:"11 yrs", fee:499, rating:4.6, initial:"PN" },
  { id:"d6", name:"Dr. Vikram Rathi", spec:"Orthopedic", exp:"16 yrs", fee:449, rating:4.7, initial:"VR" },
];

const ICON = {
  pill: `<svg class="cat-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3.5" y="9.5" width="17" height="7" rx="3.5" transform="rotate(-35 12 13)"/><line x1="10.5" y1="7.5" x2="15" y2="18.5"/></svg>`,
  shield: `<svg class="cat-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l7 3v6c0 4.5-3 7.5-7 9-4-1.5-7-4.5-7-9V6l7-3Z"/></svg>`,
  droplet: `<svg class="cat-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3s6 7 6 11.5a6 6 0 0 1-12 0C6 10 12 3 12 3Z"/></svg>`,
  heart: `<svg class="cat-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 20s-7-4.4-9.5-9C.7 7.2 3 4 6.5 4 9 4 11 6 12 7.5 13 6 15 4 17.5 4 21 4 23.3 7.2 21.5 11 19 15.6 12 20 12 20Z"/></svg>`,
  flame: `<svg class="cat-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3c1 3-2 4-2 7a4 4 0 0 0 8 0c0-1-.4-1.8-1-2.5.6 2-1 3-2 3-1.5 0-1.3-1.7-1.5-3C13.2 5.5 12 3 12 3Z"/></svg>`,
  wind: `<svg class="cat-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 8h11a2.5 2.5 0 1 0-2.5-2.5"/><path d="M3 13h15a2.5 2.5 0 1 1-2.5 2.5"/></svg>`,
  leaf: `<svg class="cat-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 4c0 9-5 15-14 15H4v-2C4 9 10 4 20 4Z"/></svg>`,
  activity: `<svg class="cat-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 12h4l2.5-8 4 16 2.5-8H21"/></svg>`,
};